# Generated by Django 4.2.10 on 2024-03-14 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myadmin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(default="", max_length=12)),
            ],
            options={"db_table": "area",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=20)),
            ],
            options={"db_table": "City",},
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20)),
                ("decoration", models.TextField(default="", max_length=20)),
                ("address", models.TextField(default="", max_length=100)),
                ("date", models.DateField(default=datetime.date.today)),
                ("status", models.CharField(default="pending", max_length=100)),
                (
                    "area",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.area",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myadmin.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.city",
                    ),
                ),
            ],
            options={"db_table": "donation",},
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("contact", models.BigIntegerField()),
                ("message", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
            options={"db_table": "inquiry",},
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20)),
            ],
            options={"db_table": "role",},
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=20)),
            ],
            options={"db_table": "State",},
        ),
        migrations.CreateModel(
            name="Requestevents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20)),
                ("description", models.CharField(default="", max_length=20)),
                ("eventtype", models.CharField(default="", max_length=20)),
                ("date", models.DateField(default=datetime.date.today)),
                ("status", models.CharField(default="", max_length=20)),
                ("remarks", models.TextField(default="")),
                (
                    "area",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.area",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.city",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "requestevents",},
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.BigIntegerField()),
                ("dob", models.DateField()),
                ("address", models.TextField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=255)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.area"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.city"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.role"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "register",},
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ratings", models.CharField(max_length=10)),
                ("comment", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "feedback",},
        ),
        migrations.CreateModel(
            name="Donation_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved_datetime",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("approved_remarks", models.TextField(default="")),
                ("received_datetime", models.CharField(default="", max_length=20)),
                ("received_remarks", models.TextField(default="")),
                ("delivered_datetime", models.CharField(default="", max_length=20)),
                ("delivered_remarks", models.TextField(default="")),
                (
                    "donation",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.donation",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "donation_status",},
        ),
        migrations.AddField(
            model_name="donation",
            name="state",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.state"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Donate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
                ("description", models.TextField(default="", max_length=100)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "donate",},
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.state"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="city",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.city"
            ),
        ),
    ]
