# Generated by Django 4.2.10 on 2024-03-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="address",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="area",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.area"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="city",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.city"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="contact",
            field=models.BigIntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="register",
            name="date",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="dob",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="register",
            name="gender",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="register",
            name="image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="register",
            name="role",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="user.role"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
