# Generated by Django 4.2.10 on 2024-03-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_register_address_alter_register_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
