# Generated by Django 4.2.10 on 2024-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_donation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
